version: "3"

services:
  paper:
    environment:
      JVM_ARGS: "-Xmx8G"
      MC_RELEASE: "1.15.2"
      PAPER_BUILD: "latest"
      USER: "1000"
      GROUP: "1000"
    volumes:
      - "./paper/data:/data"
    build:
      context: ./paper
    ports:
      - "25565:25565"
    restart: "always"
    stdin_open: true
    tty: true