#!/bin/bash

# Define functions
get_jar () {
    echo Getting Paper build $NEW_PAPER_BUILD for Minecraft $NEW_MC_RELEASE...
    wget -q https://papermc.io/api/v1/paper/$NEW_MC_RELEASE/$NEW_PAPER_BUILD/download -O /data/paper.jar
    echo Done!
}

echo ========== UPDATER ==========
if [ ! -f "/data/paper.jar" ]; then
    echo It appears you have not downloaded Paper yet.
    NEW_MC_RELEASE=$MC_RELEASE
    NEW_PAPER_BUILD=$PAPER_BUILD
    get_jar
else
    # Get Paper version
    echo Checking Paper version...
    CURRENT_PAPER_BUILD=$(java -jar /data/paper.jar -v | grep -oE "[^-]+$")
    CURRENT_MC_RELEASE=$(unzip -p paper.jar patch.properties | grep -oE -m1 "version=.+" | cut -d"=" -f2)
    CURRENT_VERSION_HASH=$(echo $CURRENT_MC_RELEASE:$CURRENT_PAPER_BUILD | openssl dgst -sha256)
    echo You have Paper build $CURRENT_PAPER_BUILD for Minecraft $CURRENT_MC_RELEASE.

    # Check for updates (or switch build / Minecraft version)
    echo Checking for updates...
    NEW_VERSION_INFO=$(curl -Ss https://papermc.io/api/v1/paper/$MC_RELEASE/$PAPER_BUILD)
    NEW_MC_RELEASE=$(echo $NEW_VERSION_INFO | jq -r ".version")
    NEW_PAPER_BUILD=$(echo $NEW_VERSION_INFO | jq -r ".build")
    NEW_VERSION_HASH=$(echo $NEW_MC_RELEASE:$NEW_PAPER_BUILD | openssl dgst -sha256)

    if [ "$CURRENT_VERSION_HASH" != "$NEW_VERSION_HASH" ]; then
        echo Update available!
        get_jar
    else
        echo No updates available.
    fi
fi

# Start the server
exec /start